### ISSUE TITLE
bugs to fix

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#16]
**EDIT** all this is living on the [reactivity-fix](https://github.com/Metropolitan-Council/regionalparks.acs/tree/reactivity-fix) branch, and working well!

- [ ] leaflet not autopopulating with selected (or checked) input. (i.e. `mod_input_demos` has:
`
                <div class='radio'>
                  <label>
                    <input type='radio' name='input_demos_ui_1-inputCensusTracts' value='Age, 18-39' checked='checked'>
                    <span>Age, 18-39</span>
                  </label>
                </div>
`
and yet when the map loads the tract data is empty.

- [x] consider adding html to `mod_summary_selections` so that the "status" input has colored text to match with the existing/planned/search point (or leaflet polys) colors (can col by `e_col`, `p_col`, `s_col`)

- [x] `mod_summary_plot` should have the height on `plotlyOutput(ns('output_plot')) responding to the `nrow()` of selected data. Have tried a couple thigns that aren't working....

- [x] `mod_summary_plot` is reporting the agency average ACS demographic information in text form (under the legend, before the plotly). However, new lines are not being inserted... `  output$avgtext <- renderText(
    (paste0("\nAverage ", '"', (summary_util$plot_buffer_data[1,6] %>%
            ....... 
           summary_util$agencyavg_data$value, "       ", "\n")))`

- [x] aesthetically, what do we think about colors? (I've snagged colors from [here](https://jfly.uni-koeln.de/color/) but it's a bit hard to reconcile good leaflet polygon colors with everything (currently, in the new maps, I've opted for a single color palette (ie purples / blues).

**Comment by eroten** [comment]
For item 3, `mod_summary_plot` height: I would suggest that we rearrange the panels in the "ACS Summary" tab so that the inputs are on the left and "View Data" tab panel is on the right. This will help conserve space, and will narrow the plot, since the x-axis has a relatively short range. 

I also think that there are diminishing returns for viewing more parks (more elements on the y-axis) in this plot. We may want to limit the number of agencies the user can select so that the plot height stays manageable. 

We (generally) want to keep as much of the content within the original view of the page (no scrolling). We could put the tabular data table further down and keep the most important sections of the viz in immediate view. 

If we want to show an agency-level comparison, we could also make a separate "mini" plot with only the agency-level metrics (rather than have a vertical line).

**Comment by eroten** [comment]
@ehesch I'm checking in on this issue to make sure it hasn't gone stale and to tidy up our to-do list. I checked off items that aren't relevant or have been completed. The only one remaining is the leaflet rendering on startup, which is mentioned in #24.

I'm closing this issue, and we can re-open it if necessary.
