### ISSUE TITLE
Snappy title

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/regionalparks.acs#34]
We need a snappy title for this app! Previous titles

- Regional Parks and the American Community Survey

**Comment by ehesch** [comment]
@eroten I think/hope there's an opportunity to think about this in a rather grandiose manner (in the future, I agree that a more immediate and smaller solution is needed!). As in, could this "app" be thought of as a landing page for the _ecosystem of parks data_ rather than just an interactive equity piece?

How sweet would it be if *anyone* (but primarily agencies) could interact with:
- equity metrics (this piece!)
- use data (past/future data on park visitor studies and/or streetlight data (even if password protected)?)
- natural resource data (maybe ecosystem service valuation?)
- other??!?!?

"Regional Park & Trail Explorer" 😴
"Regional Park and Trail Data Hub" 🧐
"Park and Trail Data Dashboard" (a bit misleading, but maybe only 🤓  care)

---
Immediate ideas:
Regional Parks Population Explorer? Regional Park and Trail Equity Metrics? meh. It's too bad that the "parks equity toolkit" already refers to a set of questions, rather than a true toolkit with multiple tools (question tool, mapping tool, etc.)
