### ISSUE TITLE
css font size

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#41]
@kryba-tures mentioned that the font size isn't adhering to the shiny design guide (it's too small). Changing to css to be "pt" rather than "px" made the font sizes bigger. But it's still not right, becuase the design guide *does* specify that text should be in px. Inspecting the various elements of the metrocouncil.org's css and our css....well, I don't know why our (app) text is rendering smaller than the (council's) website text. 

It would be great if the app css could go back to px. But in the meantime, pt seems to be a happy medium. Would welcome @eroten ' s tips!

**Comment by eroten** [comment]
I agree that the font sizes overall are too small. I've been increasing the font sizes from what is in the style guide in another project I'm working on, making sure to keep some hierarchy. 

I don't know why it would be rendering differently though! Double check that you don't have your browser zoomed in (I regularly zoom most sites to 110% because 👓)
