### ISSUE TITLE
Cherokee Regional Park

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/regionalparks.acs#54]
Darcie mentioned that Cherokee Regional Park is missing from the tool. Is it grouped with Lilydale, but not labelled as a such?

https://www.stpaul.gov/facilities/cherokee-regional-park

**Comment by ehesch** [comment]
@eroten your hunch is correct: 

I just downloaded the latest park data; and I would recommend that the "fix" for this happens *upstream* of the app; aka the [MN geospatial commons file located here](https://gisdata.mn.gov/dataset/us-mn-state-metc-plan-parks-regional)! And/or maybe flagging for Tracey's GIS improvement project :) Why there? Because if we start manually fixing these things, we're gonna start having problems all over (i.e., the streetlight project also pulls the most recent data from the mn geospatial commons file, etc.)  

In the meantime, yes the name is "lilydate-harriet island regional park" with the IA of St. Paul.

![Screen Shot 2022-03-07 at 9 12 33 AM](https://user-images.githubusercontent.com/69309226/157061541-ead613b1-1e1a-4ef6-8031-bc0de5da61fb.png)
